FROM php:7.3.3-apache
#RUN apt-get update && apt-get upgrade -y 
RUN docker-php-ext-install mysqli

ENV COMPOSER_ALLOW_SUPERUSER=1  \
	SERVERNAME="localhost"      \
	HTTPS="on"                  \
	OJS_VERSION=3_3_0-9 \
	OJS_CLI_INSTALL="0"         \
	OJS_DB_HOST="localhost"     \
	OJS_DB_USER="ojs"           \
	OJS_DB_PASSWORD="ojs"       \
	OJS_DB_NAME="ojs"           \
	OJS_WEB_CONF="/etc/apache2/conf.d/ojs.conf"	\
	OJS_CONF="/var/www/html/config.inc.php"


# PHP_INI_DIR to be symmetrical with official php docker image
ENV PHP_INI_DIR /etc/php/7.3

# Basic packages
ENV PACKAGES 		\
	apache2 		\
	apache2-ssl 	\
	apache2-utils 	\
	ca-certificates \
	curl 			\
	ttf-freefont	\
	dcron 			\
	patch			\
	php7			\
	php7-apache2	\
	runit

# PHP extensions
ENV PHP_EXTENSIONS	\
	php7-bcmath		\
	php7-bz2		\
	php7-calendar	\
	php7-ctype		\
	php7-curl		\
	php7-dom		\
	php7-exif		\
	php7-fileinfo	\
	php7-ftp		\
	php7-gettext	\
	php7-intl		\
	php7-iconv		\
	php7-json		\
	php7-mbstring	\
	php7-mysqli		\
	php7-opcache	\
	php7-openssl	\
	php7-pdo_mysql	\
	php7-phar		\
	php7-posix		\
	php7-session	\
	php7-shmop		\
	php7-simplexml	\
	php7-sockets	\
	php7-sysvmsg	\
	php7-sysvsem	\
	php7-sysvshm	\
	php7-tokenizer	\
	php7-xml		\
	php7-xmlreader	\
	php7-xmlwriter	\
	php7-zip		\
	php7-zlib

# Required to build OJS:
ENV BUILDERS 		\
	git 			\
	nodejs 			\
	npm


EXPOSE 80
