export const messages = [
  {
    id: 'bd7acbea-c1b1-46c2-aed5-3ad53abb28ba',
		avatar: require('./assets/Avatars/Avatar1.png'),
		uname: 'Артем Франк',
		uid: 1,
    text: 'Кстати, соседи, что думаете по поводу постройки новой детской площадки? Было бы хорошо, чтобы дети могли играть прямо во дворе',
  },
  {
    id: '3ac68afc-c605-48d3-a4f8-fbd91aa97f63',
		avatar: require('./assets/Avatars/Avatar2.png'),
		uname: 'Михаил Буцкий',
		uid: 2,
    text: 'Артём, хорошая идея, нужно бы узнать к кому нужно обращаться за помощью в постройке площадки',
  },
  {
    id: '58694a0f-3da1-471f-bd96-145571e29d72',
		avatar: require('./assets/Avatars/Avatar3.png'),
		uname: 'Вадим Цап',
    uid: 2,
		text: 'Тоже так думаю',
  },
  {
    id: 'bd7acbea-c151-46c2-aed5-3ad53abb28ba',
		avatar: require('./assets/Avatars/Avatar1.png'),
		uname: 'Артем Франк',
		uid: 1,
    text: 'Кстати, соседи, что думаете по поводу постройки новой детской площадки? Было бы хорошо, чтобы дети могли играть прямо во дворе',
  },
  {
    id: '3ac68afc-c645-48d3-a4f8-fbd91aa97f63',
		avatar: require('./assets/Avatars/Avatar2.png'),
		uname: 'Михаил Буцкий',
		uid: 2,
    text: 'Артём, хорошая идея, нужно бы узнать к кому нужно обращаться за помощью в постройке площадки',
  },
  {
    id: '58694a0f-3d61-471f-bd96-145571e29d72',
		avatar: require('./assets/Avatars/Avatar3.png'),
		uname: 'Вадим Цап',
    uid: 2,
		text: 'Тоже так думаю',
  },
  {
    id: 'bd7acbea-c7b1-46c2-aed5-3ad53abb28ba',
		avatar: require('./assets/Avatars/Avatar1.png'),
		uname: 'Артем Франк',
		uid: 1,
    text: 'Кстати, соседи, что думаете по поводу постройки новой детской площадки? Было бы хорошо, чтобы дети могли играть прямо во дворе',
  },
  {
    id: '3ac68afc-c905-48d3-a4f8-fbd91aa97f63',
		avatar: require('./assets/Avatars/Avatar2.png'),
		uname: 'Михаил Буцкий',
		uid: 2,
    text: 'Артём, хорошая идея, нужно бы узнать к кому нужно обращаться за помощью в постройке площадки',
  },
  {
    id: '58694a0f-3da1-471f-bd66-145571e29d72',
		avatar: require('./assets/Avatars/Avatar3.png'),
		uname: 'Вадим Цап',
    uid: 2,
		text: 'Тоже так думаю',
  },
  {
    id: 'bd7acbea-c1b1-46c2-a2d5-3ad53abb28ba',
		avatar: require('./assets/Avatars/Avatar1.png'),
		uname: 'Артем Франк',
		uid: 1,
    text: 'Кстати, соседи, что думаете по поводу постройки новой детской площадки? Было бы хорошо, чтобы дети могли играть прямо во дворе',
  },
  {
    id: '3ac68afc-c605-44d3-a4f8-fbd91aa97f63',
		avatar: require('./assets/Avatars/Avatar2.png'),
		uname: 'Михаил Буцкий',
		uid: 2,
    text: 'Артём, хорошая идея, нужно бы узнать к кому нужно обращаться за помощью в постройке площадки',
  },
  {
    id: '58694a0f-3da1-475f-bd96-145571e29d72',
		avatar: require('./assets/Avatars/Avatar3.png'),
		uname: 'Вадим Цап',
    uid: 2,
		text: 'Тоже так думаю',
  },
];

export const chats = [
  {
    id: 'bd7acbea-c1b1-46c2-aed5-3ad53abb28ba',
		avatar: require('./assets/Avatars/Avatar1.png'),
		uname: 'Артем Франк',
    text: 'Кстати, соседи, что думаете по поводу постройки новой детской площадки? Было бы хорошо, чтобы дети могли играть прямо во дворе',
  },
  {
    id: '3ac68afc-c605-48d3-a4f8-fbd91aa97f63',
		avatar: require('./assets/Avatars/Avatar2.png'),
		uname: 'Михаил Буцкий',
		uid: 2,
    text: 'Артём, хорошая идея, нужно бы узнать к кому нужно обращаться за помощью в постройке площадки',
  },
];
